version: "3.1"
services:
  cabeleleira-leila-web:
    container_name: cabeleleira-leila-web
    restart: always
    image: frontend:latest
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/cabeleleira-leila-web
      - ./cabeleleira-leila-web/node_modules
    command: ng serve --host 0.0.0.0 --port 4200